### ISSUE TITLE
Add authors and Wiley URLs to journal articles missing them

### ISSUE THREAD

**Issue by caseyg** [caseyg/americanethnologist#29]

**Comment by daveleins8** [comment]
Encountered an odd issue with authors names on **unsorted articles**:

http://aes-dev.caseyagollan.com/read/journal/test/ferguson-digital-protest-hashtag-ethnography-and-the-racial-politics-of-social-media-in-the-united-states

http://aes-dev.caseyagollan.com/read/journal/test/anthropologyferguson-missouri

After entering authors' names in the fields, the diagnostic shows the update, which is good, but there are two glitchy things going on:
[1] - When I try to save changes, instead of getting the green 'saved' notification in the upper right, I get a red one (although the changes appear to save acc. to diagnostic site)

[2] - The authors' names don't actually show up on the article page, as you can see in the links above. 

Here's some screenshots:

![screenshot 2017-01-23 at 9 01 47 pm](https://cloud.githubusercontent.com/assets/24961890/22231149/95c1f034-e1af-11e6-8e42-187f41d27dc7.png)
![screenshot 2017-01-23 at 9 01 20 pm](https://cloud.githubusercontent.com/assets/24961890/22231151/95c3e4b6-e1af-11e6-8eff-526c4b1d38e5.png)
![screenshot 2017-01-23 at 9 01 04 pm](https://cloud.githubusercontent.com/assets/24961890/22231150/95c2188e-e1af-11e6-8d08-5455f62aeef0.png)

**Comment by daveleins8** [comment]
Here's another example from **unsorted articles** where I save changes, but it doesn't seem to go through, here's what I see after attempting to save:

![screenshot 2017-01-23 at 9 20 04 pm](https://cloud.githubusercontent.com/assets/24961890/22231465/ce52d51a-e1b1-11e6-8ea7-efbf6fc560ba.png)

**Comment by daveleins8** [comment]
It looks like the error is:

"The directory could not be moved"

![screenshot 2017-01-23 at 9 24 55 pm](https://cloud.githubusercontent.com/assets/24961890/22231579/7242bf14-e1b2-11e6-895c-697831c3d6ea.png)

**Comment by caseyg** [comment]
Weird—I will look into this. Thanks for the detailed debugging!

**Comment by caseyg** [comment]
Closing this, since this seems mostly worked out.
