### ISSUE TITLE
Awards pages: reverse chronological order

### ISSUE THREAD

**Issue by daveleins8** [caseyg/americanethnologist#53]
Can we have award winners display in reverse chronological order? 

As of now, I have ordered the oldest awards first (e.g. 2003 winner , ranking #1; 2004 winner, ranking #2, etc).

This way, as we add awards in the future, we don't have to re-order the whole list to make the newest addition ranked #1. Does this make sense? Here's the link and a screenshot for reference:

http://aes-dev.caseyagollan.com/awards

![screenshot 2017-01-23 at 8 36 55 pm](https://cloud.githubusercontent.com/assets/24961890/22230468/b4790fe8-e1ab-11e6-9f87-9175440f1efc.png)
![screenshot 2017-01-23 at 8 36 46 pm](https://cloud.githubusercontent.com/assets/24961890/22230469/b4832000-e1ab-11e6-91f9-2342776e817a.png)

**Comment by caseyg** [comment]
Yes, this makes a lot of sense — will fix!

**Comment by caseyg** [comment]
Is this what you meant, @daveleins8?

![screen shot 2017-01-26 at 6 03 19 pm](https://cloud.githubusercontent.com/assets/462020/22353967/0c375022-e3f1-11e6-96fd-3782d683b403.png)

I switched the sort direction (though it remains the same on the frontend), and also switched from year-based to manual sort, so that you can adjust the order of winners & honorable mentions as needed.

**Comment by daveleins8** [comment]
Yep, perfect.
