### ISSUE TITLE
Left-navigation edit access for Dave

### ISSUE THREAD

**Issue by daveleins8** [caseyg/americanethnologist#75]
Is it possible to give me control over the navigation on page modules. Right now I'm working on meetings pages, and if I could have a markdown tag that feeds the left-nav, then I could easily mark the sub-headers that I use to do so. Example below:

![screenshot 2017-03-06 at 11 00 35 am](https://cloud.githubusercontent.com/assets/24961890/23617771/23fb6ea8-025c-11e7-8790-89d53db76766.png)

I'd like to be able to make **proposals**, **deadlines**, etc. appear on the left-nav, if possible.

-DJL

**Comment by caseyg** [comment]
Right now the left nav for meeting pages is an autogenerated list of modules, but for this page you're putting all sections in one modules as markdown subheadings. 

See, for example, how this meeting's sections are broken into modules instead of just being markdown subheadings: 
http://americanethnologist.org/meetings/spring-conference/aes-2017-exposure

Does that make sense or is that super annoying? Can change it if so — LMK!

**Comment by daveleins8** [comment]
It isn't super annoying. I can add new modules knowing they are the nav sections going forward. It would be nice to be able to add something to the nav. A lot of these meetings pages grow over several months from being stubs to having tons of sections, so I then have to break them apart when they grow too big/ we get all of our information posted. 

For now though, I'm fine with breaking into different modules like I have on other sections of the site.
