### ISSUE TITLE
Login problem

### ISSUE THREAD

**Issue by daveleins8** [caseyg/americanethnologist#98]
Priority: High
8/28/17

I'm receiving an alert from Chrome letting me know the site isn't secure when I try to log in. Unfortunately, I can't log in to the admin panel unless I use an incognito tab. I don't know why this is exactly. I've tried a new password, clearing cache, cookies, etc. But I can't log in.

My hunch is that it is related to the 'site not secure' warning I'm getting. Can you advise on this? See screenshot below:

![screenshot 2017-08-28 at 6 55 04 pm](https://user-images.githubusercontent.com/24961890/29797469-37ed2df4-8c25-11e7-8f88-4f4f9dc3c30a.png)

**Comment by caseyg** [comment]
Hey @daveleins8! This is probably unrelated to the security of the site, which is pretty standard. (The more secure "HTTPS" protocol this is prompting you about is a must for websites which exchange things like financial data from many users, but not really necessary for AES in my opinion.)

The fact that it works in a private window lets me know that the problem is with your browser. I also have no problems logging in on my end.

Can you try clearing your cookies and seeing if this fixes you login?

https://support.google.com/chrome/answer/95647

**Comment by daveleins8** [comment]
Shoot I did clear cookies before and no luck. I'll just keep
troubleshooting on my end, no worries.
